# -*- coding: utf-8 -*-
"""DMDW_CASE _STUDY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IivVwGZ8XTjF4g4Eg-GCOTrIOk_mCvMB
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Load the dataset
# Assuming the dataset is in CSV format after conversion from PDF
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')


# Display the first few rows of the dataset
print("First few rows of the dataset:")
print(data.head(10))

# Data Cleaning
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')  # Convert date to datetime format
data = data.dropna()  # Drop rows with missing values

# Trend Analysis
# Extracting year from date for trend analysis
data.loc[:, 'Year'] = data['Date'].dt.year

# Calculate average goals per year
trend_data = data.groupby('Year').agg({'FTHG': 'mean', 'FTAG': 'mean'}).reset_index()

print("\nAverage Goals per Year:")
print(trend_data)

# Correlation Analysis
correlation_matrix = data[['FTHG', 'FTAG', 'Attendance']].corr()
print("\nCorrelation Matrix:")
print(correlation_matrix)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Load the dataset
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')

# Data Cleaning
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')  # Convert date to datetime format
data.dropna(inplace=True)  # Drop rows with missing values

# Feature Engineering
data['HomeWin'] = (data['FTR'] == 'H').astype(int)  # Binary target variable for home win

# Select features and target variable
features = data[['FTHG', 'FTAG', 'Attendance']]
target = data['HomeWin']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression Model
logistic_model = LogisticRegression()
logistic_model.fit(X_train_scaled, y_train)
y_pred_logistic = logistic_model.predict(X_test_scaled)

# Decision Tree Model
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train_scaled, y_train)
y_pred_tree = decision_tree_model.predict(X_test_scaled)

# Random Forest Model
random_forest_model = RandomForestClassifier()
random_forest_model.fit(X_train_scaled, y_train)
y_pred_forest = random_forest_model.predict(X_test_scaled)

# Evaluate Models
print("Logistic Regression Results:")
print(classification_report(y_test, y_pred_logistic))
print("Accuracy:", accuracy_score(y_test, y_pred_logistic))

print("\nDecision Tree Results:")
print(classification_report(y_test, y_pred_tree))
print("Accuracy:", accuracy_score(y_test, y_pred_tree))

print("\nRandom Forest Results:")
print(classification_report(y_test, y_pred_forest))
print("Accuracy:", accuracy_score(y_test, y_pred_forest))

import pandas as pd

# Load the dataset
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')

# Data Cleaning
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')  # Convert date to datetime format
data.dropna(inplace=True)  # Drop rows with missing values

# Initialize a list to hold team statistics
team_stats = []

# Calculate overall performance metrics for each team
for team in pd.concat([data['HomeTeam'], data['AwayTeam']]).unique():
    home_matches = data[data['HomeTeam'] == team]
    away_matches = data[data['AwayTeam'] == team]

    total_wins = (home_matches['FTR'] == 'H').sum() + (away_matches['FTR'] == 'A').sum()
    total_draws = (home_matches['FTR'] == 'D').sum() + (away_matches['FTR'] == 'D').sum()
    total_losses = (home_matches['FTR'] == 'A').sum() + (away_matches['FTR'] == 'H').sum()

    goals_scored = home_matches['FTHG'].sum() + away_matches['FTAG'].sum()
    goals_conceded = home_matches['FTAG'].sum() + away_matches['FTHG'].sum()

    # Append team statistics to the list
    team_stats.append({
        'Team': team,
        'Wins': total_wins,
        'Draws': total_draws,
        'Losses': total_losses,
        'Goals Scored': goals_scored,
        'Goals Conceded': goals_conceded,
        'Goal Difference': goals_scored - goals_conceded,
        'Total Matches': home_matches.shape[0] + away_matches.shape[0],
        'Win Rate (%)': (total_wins / (home_matches.shape[0] + away_matches.shape[0])) * 100
    })

# Create a DataFrame from the list of team statistics
teams = pd.DataFrame(team_stats)

# Display the team performance metrics
print("Team Performance Metrics:")
print(teams.sort_values(by='Wins', ascending=False).reset_index(drop=True))

import pandas as pd

# Load the dataset
df = pd.read_excel('Modified_La_Liga_Dataset_with_Titles.xlsx')

# Group by HomeTeam and calculate total titles, total goals (home and away), and total attendance (home and away)
team_stats = df.groupby('HomeTeam').agg(
    total_titles=('No of Titles', 'max'),  # max because each team has one entry for its titles
    total_goals_home=('FTHG', 'sum'),  # Home team goals
    total_attendance_home=('Attendance', 'sum')  # Home team attendance
).reset_index()

# Add away goals and away attendance
away_goals = df.groupby('AwayTeam').agg(
    total_goals_away=('FTAG', 'sum'),  # Away team goals
    total_attendance_away=('Attendance', 'sum')  # Away team attendance
).reset_index()

# Merge home and away stats into one dataframe
team_stats = pd.merge(team_stats, away_goals, left_on='HomeTeam', right_on='AwayTeam', how='left')

# Update total goals and total attendance
team_stats['total_goals'] = team_stats['total_goals_home'] + team_stats['total_goals_away']
team_stats['total_attendance'] = team_stats['total_attendance_home'] + team_stats['total_attendance_away']

# Sort teams by number of titles, goals scored, and total attendance
top_teams = team_stats.sort_values(by=['total_titles', 'total_goals', 'total_attendance'], ascending=False)

# Instead of using ace_tools, display the dataframe using pandas' display function
# or print the first few rows using head()
display(top_teams)
# Alternatively:
# print(top_teams.head())

import pandas as pd

# Load the dataset
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')

# Data Cleaning
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')  # Convert date to datetime format
data.dropna(inplace=True)  # Drop rows with missing values

# Extract season from the Date
data['Season'] = data['Date'].dt.year.astype(str) + '-' + (data['Date'].dt.year + 1).astype(str)

# Initialize a list to hold team statistics
all_team_stats = []

# Calculate overall performance metrics for each team per season
for season in data['Season'].unique():
    season_data = data[data['Season'] == season]

    for team in pd.concat([season_data['HomeTeam'], season_data['AwayTeam']]).unique():
        home_matches = season_data[season_data['HomeTeam'] == team]
        away_matches = season_data[season_data['AwayTeam'] == team]

        total_wins = (home_matches['FTR'] == 'H').sum() + (away_matches['FTR'] == 'A').sum()
        total_draws = (home_matches['FTR'] == 'D').sum() + (away_matches['FTR'] == 'D').sum()
        total_losses = (home_matches['FTR'] == 'A').sum() + (away_matches['FTR'] == 'H').sum()

        goals_scored = home_matches['FTHG'].sum() + away_matches['FTAG'].sum()
        goals_conceded = home_matches['FTAG'].sum() + away_matches['FTHG'].sum()

        # Append team statistics to the list
        all_team_stats.append({
            'Team': team,
            'Season': season,
            'Wins': total_wins,
            'Draws': total_draws,
            'Losses': total_losses,
            'Goals Scored': goals_scored,
            'Goals Conceded': goals_conceded,
            'Goal Difference': goals_scored - goals_conceded,
            'Total Matches': home_matches.shape[0] + away_matches.shape[0],
            'Win Rate (%)': (total_wins / (home_matches.shape[0] + away_matches.shape[0])) * 100
        })

# Create a DataFrame from the list of team statistics
teams_performance = pd.DataFrame(all_team_stats) # Create DataFrame outside the loop

# Display the aggregated team performance metrics
print("Team Performance Metrics Over Multiple Seasons:")
print(teams_performance.sort_values(by=['Season', 'Wins'], ascending=[True, False]).reset_index(drop=True))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the dataset (assuming it has been converted from PDF to CSV)
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')

# Data Cleaning
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')  # Convert date to datetime format
data.dropna(inplace=True)  # Drop rows with missing values

# Extract season from the Date
data['Season'] = data['Date'].dt.year.astype(str) + '-' + (data['Date'].dt.year + 1).astype(str)

# Calculate average goals and win rate for each team
team_stats = pd.DataFrame()

for team in pd.concat([data['HomeTeam'], data['AwayTeam']]).unique():
    home_matches = data[data['HomeTeam'] == team]
    away_matches = data[data['AwayTeam'] == team]

    total_goals_scored = home_matches['FTHG'].sum() + away_matches['FTAG'].sum()
    total_matches = home_matches.shape[0] + away_matches.shape[0]
    total_wins = (home_matches['FTR'] == 'H').sum() + (away_matches['FTR'] == 'A').sum()

    avg_goals_scored = total_goals_scored / total_matches if total_matches > 0 else 0
    win_rate = (total_wins / total_matches) * 100 if total_matches > 0 else 0

    # Use pd.concat instead of append
    team_stats = pd.concat([team_stats, pd.DataFrame([{
        'Team': team,
        'Avg Goals Scored': avg_goals_scored,
        'Win Rate (%)': win_rate
    }])], ignore_index=True)

# Prepare data for model training
X = team_stats[['Avg Goals Scored', 'Win Rate (%)']]
y = (team_stats['Win Rate (%)'] > 50).astype(int)  # Binary target: 1 if win rate > 50%, else 0

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Evaluate model accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Load the dataset
data = pd.read_excel('LaLiga_Matches_With_Attendance.xlsx')  # Replace with your actual dataset path

# Step 2: Display the first few rows of the dataset
print(data.head())

# Step 3: Feature Engineering
# Convert categorical variables to numerical (e.g., HomeTeam and AwayTeam)
data['HomeTeam'] = data['HomeTeam'].astype('category').cat.codes
data['AwayTeam'] = data['AwayTeam'].astype('category').cat.codes

# Create a target variable: 1 for home win, 0 for draw, -1 for away win
data['Result'] = np.where(data['FTR'] == 'H', 1, np.where(data['FTR'] == 'D', 0, -1))

# Select features and target variable
features = data[['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]  # Add more features as needed
target = data['Result']

# Step 4: Split the Data
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Step 5: Train the Model
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

# Step 6: Make Predictions on the Test Set
y_pred = model.predict(X_test)

# Evaluate the model performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Step 7: Predict Future Matches
# Example future matches DataFrame (replace with actual match data)
future_matches = pd.DataFrame({
    'HomeTeam': [1, 2],
    'AwayTeam': [3, 4],
    'FTHG': [1, 1],
    'FTAG': [1, 1]
})

# Predict outcomes for future matches
future_predictions = model.predict(future_matches)
print("Future Predictions (1: Home Win, 0: Draw, -1: Away Win):", future_predictions)  # Output will be 1 (home win), 0 (draw), -1 (away win)

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans # Importing KMeans for clustering


# Upload the file
uploaded = files.upload()

# Load the file into a DataFrame
# Replace 'LaLiga_Matches_With_Attendance.xlsx' with the actual file name after uploading
df = pd.read_excel(next(iter(uploaded)))
df.head()


# 1. Histogram (Attendance)
plt.figure(figsize=(8, 6))
plt.hist(df['Attendance'].dropna(), bins=20, color='skyblue', edgecolor='black') # Changed 'data' to 'df'
plt.title('Histogram of Attendance')
plt.xlabel('Attendance')
plt.ylabel('Frequency')
plt.show()

# 2. Box Plot (Home and Away Goals)
plt.figure(figsize=(8, 6))
sns.boxplot(data=[df['FTHG'].dropna(), df['FTAG'].dropna()])  # Changed 'data' to 'df'
plt.xticks([0, 1], ['Home Goals', 'Away Goals'])
plt.title('Box Plot of Home and Away Goals')
plt.ylabel('Goals')
plt.show()


# 4. Pie Chart (Match Results)
result_counts = df['FTR'].value_counts()  # Changed 'data' to 'df'
plt.figure(figsize=(6, 6))
plt.pie(result_counts, labels=result_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Pie Chart of Match Results')
plt.show()

# 5. Bar Chart (Average Attendance per Season)
attendance_per_season = df.groupby('Season')['Attendance'].mean()  # Changed 'data' to 'df'
plt.figure(figsize=(12, 6))
attendance_per_season.plot(kind='bar', color='coral')
plt.title('Average Attendance per Season')
plt.xlabel('Season')
plt.ylabel('Average Attendance')
plt.show()

# K-means Clustering (Home Goals and Attendance)
# Defining clustering_data and performing KMeans clustering
clustering_data = df[['FTHG', 'Attendance']].dropna()  # Using 'df' instead of 'data'
kmeans = KMeans(n_clusters=3, random_state=0)
clustering_data['Cluster'] = kmeans.fit_predict(clustering_data[['FTHG', 'Attendance']])

plt.figure(figsize=(8, 6))
plt.scatter(clustering_data['FTHG'], clustering_data['Attendance'], c=clustering_data['Cluster'], cmap='viridis')
plt.title('K-means Clustering of Home Goals vs. Attendance')
plt.xlabel('Home Goals (FTHG)')
plt.ylabel('Attendance')
plt.colorbar(label='Cluster')
plt.show()

# 7. Heatmap (Correlation of Numerical Features)
numerical_cols = df.select_dtypes(include=['number']).columns
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap of Numerical Features")
plt.show()

